services:  
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4001:4001"
      - "1935:1935"
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - SHEETS_API_KEY=${SHEETS_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_OHSHEET_BACKEND_SERVER_PORT: 4001
        VITE_OHSHEET_MEDIA_SERVER_PORT: 8000
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
