FROM node:20.11.1

WORKDIR /app

COPY server/package*.json ./

RUN npm install
RUN apt-get update && apt-get install -y curl

COPY server/ ./

EXPOSE 4001
EXPOSE 1935
EXPOSE 8000

CMD ["node", "app.js"]
